# Spring properties
spring:
  data:
    mongodb:
      auto-index-creation: false
      authentication-database: admin
      username: admin
      password: mongodb
      database: employeeDB
      port: 27017
      host: 0.0.0.0
      #      uri: mongodb://localhost:27017/employeeDB

# HTTP Server
server:
  port: 8092